name: Python Setup with Datasette and Spatialite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Datasette
      run: |
        python -m pip install --upgrade pip
        pip install datasette
    
    - name: Install Spatialite
      run: |
        $spatialiteUrl = "https://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-5.0.1-win-amd64.7z"
        $spatialiteArchive = "mod_spatialite.7z"
        $spatialiteDir = "C:\spatialite"
        
        Invoke-WebRequest -Uri $spatialiteUrl -OutFile $spatialiteArchive
        7z x $spatialiteArchive -o"$spatialiteDir"
        
        $env:PATH += ";$spatialiteDir"
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Machine)
    
    - name: Verify installation
      run: |
        python -c "import sqlite3; sqlite3.enable_load_extension(True); sqlite3.load_extension('mod_spatialite')"
        datasette --version
