name: Python Setup with Datasette and Spatialite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Datasette
      run: |
        # python -m pip install pysqlite3-binary
        # pip install datasette
    - name: Download mod_spatialite
      run: Invoke-WebRequest -outfile spatialite.7z https://static.simonwillison.net/static/2024/spatialite-loadable-modules-5.0.0-win-amd64.7z
    - name: Unpack the archive
      run: 7z.exe x spatialite.7z
    - name: Show path
      run: echo $PWD\spatialite-loadable-modules-5.0.0-win-amd64
    - name: Verify installation
      run: |
        python -c "import sqlite3; sqlite3.enable_load_extension(True); sqlite3.load_extension('$env:GITHUB_WORKSPACE\spatialite-loadable-modules-5.0.0-win-amd64\mod_spatialite')"
        # datasette --version
