name: sqlite-vec on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: windows-latest
    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install sqlite-vec
      run: |
        pip install sqlite-vec
    - name: Verify installation
      run: |
        python -c @"
        import sqlite3, os
        import sqlite_vec
        db = sqlite3.Connection(':memory:')
        db.enable_load_extension(True)
        db.load_extension(sqlite_vec.loadable_path())
        print(db.execute('select vec_version()').fetchall())
        "@
