name: Tailscale exit node demo

on:
  workflow_dispatch:

jobs:
  run-with-tailscale:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show IP before Tailscale
        run: |
          echo "IP from ifconfig.me:"
          curl -s https://ifconfig.me

      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:github-actions
      - name: Use named exit node
        run: |
          timeout 5m sudo -E tailscale set --exit-node=apple-tv
      - name: Verify HTTP traffic is routed through exit node
        run: |
          echo "Available exit nodes:"
          tailscale status | grep 'exit node'

          echo "IP from ifconfig.me:"
          curl -s https://ifconfig.me
