name: uv example

on:
  workflow_dispatch:

jobs:
  uv-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: cache-cargo-bin
      uses: actions/cache@v4
      with:
        path: .cargo/bin
        key: ${{ runner.os }}-cargo-bin
    - id: cache-uv-python
      uses: actions/cache@v4
      with:
        path: .local/share/uv
        key: ${{ runner.os }}-uv-python
    - name: Install uv
      if: steps.cache-cargo-bin.outputs.cache-hit != 'true'
      run: |
        curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh
        cd $HOME
        find .cargo
    - name: Run uv
      run: |
        python -c 'import sys; print("Before:", sys.version)'
        uv python install
        cd $HOME
        uv run python -c 'import sys; print(sys.version)'
